#!/usr/bin/env bash
# Table-driven harness for scripts/kit-schema-sync.sh
#
# Exit 0 only if all cases pass.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
SCRIPT="${ROOT}/scripts/kit-schema-sync.sh"
KIT_SQL="${ROOT}/apps/example-api/migrations"
CATALOG="${ROOT}/config/kit-schema-modules.json"

if [[ ! -f "${SCRIPT}" ]]; then
  echo "FAIL: missing ${SCRIPT}" >&2
  exit 1
fi

# Catalog projection — same TSV path as the SUT (no eval of JSON.stringify).
CATALOG_IDS=()
CATALOG_FILES=()
CATALOG_SETS=()
CATALOG_SHAS=()
CORE_IDS=()
SOURCE_ROOT=""
CATALOG_TSV="$(
  KIT_SCHEMA_CATALOG="${CATALOG}" bun -e '
const fs = require("fs");
const data = JSON.parse(fs.readFileSync(process.env.KIT_SCHEMA_CATALOG, "utf8"));
if (typeof data.source_root !== "string") process.exit(1);
console.log("#SOURCE_ROOT\t" + data.source_root);
for (const m of data.modules) {
  console.log([m.id, m.file, m.set, m.kitSha256].join("\t"));
}
'
)" || { echo "FAIL: catalog extract" >&2; exit 1; }
while IFS=$'\t' read -r c1 c2 c3 c4; do
  if [[ "${c1}" == "#SOURCE_ROOT" ]]; then
    SOURCE_ROOT="${c2}"
    continue
  fi
  [[ -n "${c1}" ]] || continue
  CATALOG_IDS+=("${c1}")
  CATALOG_FILES+=("${c2}")
  CATALOG_SETS+=("${c3}")
  CATALOG_SHAS+=("${c4}")
  if [[ "${c3}" == "core" ]]; then
    CORE_IDS+=("${c1}")
  fi
done <<< "${CATALOG_TSV}"$'\n'

PASS=0
FAIL=0

pass() {
  echo "  PASS: $1"
  PASS=$((PASS + 1))
}

fail_case() {
  echo "  FAIL: $1" >&2
  if [[ -n "${2:-}" ]]; then
    echo "    $2" >&2
  fi
  FAIL=$((FAIL + 1))
}

file_sha256() {
  local f="$1"
  local out
  if command -v sha256sum >/dev/null 2>&1; then
    out="$(sha256sum -- "$f")" || return 1
  elif command -v shasum >/dev/null 2>&1; then
    out="$(shasum -a 256 -- "$f")" || return 1
  else
    echo "FAIL: need sha256sum or shasum" >&2
    return 1
  fi
  printf '%s' "${out%% *}" | tr 'A-F' 'a-f'
}

sql_count() {
  local dir="$1"
  local files=()
  local old
  old="$(shopt -p nullglob)"
  shopt -s nullglob
  files=("${dir}"/*.sql)
  eval "${old}"
  printf '%s' "${#files[@]}"
}

manifest_count() {
  local f="$1"
  if [[ ! -f "${f}" ]]; then
    printf '0'
    return
  fi
  KIT_SCHEMA_MANIFEST="$f" bun -e '
const m = JSON.parse(require("fs").readFileSync(process.env.KIT_SCHEMA_MANIFEST, "utf8"));
console.log(Object.keys(m.modules || {}).length);
'
}

manifest_field() {
  local f="$1"
  local id="$2"
  local field="$3"
  KIT_SCHEMA_MANIFEST="$f" KIT_SCHEMA_ID="$id" KIT_SCHEMA_FIELD="$field" bun -e '
const m = JSON.parse(require("fs").readFileSync(process.env.KIT_SCHEMA_MANIFEST, "utf8"));
const e = m.modules && m.modules[process.env.KIT_SCHEMA_ID];
if (!e) process.exit(2);
const v = e[process.env.KIT_SCHEMA_FIELD];
if (typeof v !== "string") process.exit(2);
console.log(v);
'
}

copy_sql_range() {
  local dest="$1"
  local start="$2"
  local end="$3"
  local n name
  mkdir -p "${dest}"
  for n in $(seq "${start}" "${end}"); do
    name="$(printf '%04d' "${n}")"
    cp "${KIT_SQL}/${name}"_*.sql "${dest}/"
  done
}

expected_appended() {
  local dest="$1"
  local id="$2"
  local kit_file="$3"
  local src_rel="$4"
  {
    printf -- '-- kit-schema: %s\n' "${id}"
    printf -- '-- kit-sha256: %s\n' "$(file_sha256 "${kit_file}")"
    printf -- '-- kit-source: %s\n' "${src_rel}"
    printf -- '-- Do not edit this file. Kit changes ship as a new module id.\n'
    printf '\n'
    cat "${kit_file}"
  } >"${dest}"
}

run_sync() {
  set +e
  RUN_OUT="$(bash "${SCRIPT}" "$@" 2>&1)"
  RUN_EC=$?
  set -e
}

echo "== kit-schema-sync =="
TMP="$(mktemp -d -t kit-schema-sync-XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

# --- 0: catalog pin vs live SQL + 1:1 listing ---
echo "-- 0 catalog pin --"
ok0=1
detail0=""
if [[ ${#CATALOG_IDS[@]} -eq 0 ]]; then
  ok0=0
  detail0="empty catalog extract"
elif [[ "$(sql_count "${KIT_SQL}")" != "${#CATALOG_IDS[@]}" ]]; then
  ok0=0
  detail0="sql=$(sql_count "${KIT_SQL}") catalog=${#CATALOG_IDS[@]}"
else
  i=0
  while [[ $i -lt ${#CATALOG_IDS[@]} ]]; do
    src="${ROOT}/${SOURCE_ROOT}/${CATALOG_FILES[$i]}"
    if [[ ! -f "${src}" ]]; then
      ok0=0
      detail0="missing ${CATALOG_FILES[$i]}"
      break
    fi
    live="$(file_sha256 "${src}")"
    if [[ "${live}" != "${CATALOG_SHAS[$i]}" ]]; then
      ok0=0
      detail0="${CATALOG_IDS[$i]} live=${live} pin=${CATALOG_SHAS[$i]}"
      break
    fi
    i=$((i + 1))
  done
fi
if [[ "${ok0}" -eq 1 ]] && git -C "${ROOT}" show origin/main:config/kit-schema-modules.json >/dev/null 2>&1; then
  set +e
  pin_drift="$(
    KIT_SCHEMA_CATALOG="${CATALOG}" bun -e '
const fs = require("fs");
const now = JSON.parse(fs.readFileSync(process.env.KIT_SCHEMA_CATALOG, "utf8"));
const prev = JSON.parse(fs.readFileSync("/dev/stdin", "utf8"));
if (!Array.isArray(prev.modules)) process.exit(1);
const nowMap = Object.fromEntries((now.modules || []).map((m) => [m.id, m.kitSha256]));
const drifted = prev.modules
  .filter((m) => m && m.id && m.kitSha256 && nowMap[m.id] && nowMap[m.id] !== m.kitSha256)
  .map((m) => m.id);
if (drifted.length) {
  console.log(drifted.join(","));
  process.exit(2);
}
' < <(git -C "${ROOT}" show origin/main:config/kit-schema-modules.json)
  )"
  pin_ec=$?
  set -e
  if [[ "${pin_ec}" -eq 2 ]]; then
    ok0=0
    detail0="published id hash changed vs origin/main: ${pin_drift}"
  elif [[ "${pin_ec}" -ne 0 ]]; then
    ok0=0
    detail0="pin-drift checker failed (exit ${pin_ec})"
  fi
fi
if [[ "${ok0}" -eq 1 ]]; then
  pass "0 catalog 1:1 + kitSha256 pins match live SQL"
else
  fail_case "0 catalog pin" "${detail0}"
fi

# --- 1: adopt on a full copy records all catalog modules, writes no SQL ---
echo "-- 1 adopt full copy --"
A1="${TMP}/case1"
mkdir -p "${A1}/migrations"
cp "${KIT_SQL}"/*.sql "${A1}/migrations/"
before_1="$(sql_count "${A1}/migrations")"
run_sync --app "${A1}" --modules all --adopt
if [[ "${RUN_EC}" -eq 0 ]]; then
  pass "1 adopt exit 0"
else
  fail_case "1 adopt exit 0" "exit ${RUN_EC}: $(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
if [[ "$(sql_count "${A1}/migrations")" == "${before_1}" && "${before_1}" == "${#CATALOG_IDS[@]}" ]]; then
  pass "1 adopt writes 0 sql (still ${#CATALOG_IDS[@]})"
else
  fail_case "1 adopt writes 0 sql" "count=$(sql_count "${A1}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
if [[ "$(manifest_count "${A1}/kit-schema-manifest.json")" == "${#CATALOG_IDS[@]}" ]]; then
  pass "1 adopt records ${#CATALOG_IDS[@]} modules"
else
  fail_case "1 adopt records ${#CATALOG_IDS[@]} modules" "count=$(manifest_count "${A1}/kit-schema-manifest.json")"
fi
got_pf="$(manifest_field "${A1}/kit-schema-manifest.json" init productFile || true)"
if [[ "${got_pf}" == "migrations/0001_init.sql" ]]; then
  pass "1 adopt productFile stays 0001_init.sql"
else
  fail_case "1 adopt productFile stays 0001_init.sql" "got=${got_pf}"
fi
# bytes unchanged (record must not rewrite)
if cmp -s "${KIT_SQL}/0001_init.sql" "${A1}/migrations/0001_init.sql"; then
  pass "1 adopt does not rewrite 0001_init.sql"
else
  fail_case "1 adopt does not rewrite 0001_init.sql"
fi

# --- 1b: --modules all --adopt on core-only copy fails and writes 0 kit files ---
echo "-- 1b adopt-all on partial clone --"
A1B="${TMP}/case1b"
copy_sql_range "${A1B}/migrations" 1 8
run_sync --app "${A1B}" --modules all --adopt
if [[ "${RUN_EC}" -ne 0 && "${RUN_OUT}" == *"adopt unmatched"* \
  && "$(sql_count "${A1B}/migrations")" == "8" \
  && ! -e "${A1B}/migrations/0009_kit_organization_roles.sql" \
  && ! -f "${A1B}/kit-schema-manifest.json" ]]; then
  pass "1b adopt-all on 0001-0008 exits 1, writes 0"
else
  fail_case "1b adopt-all on 0001-0008 exits 1, writes 0" \
    "exit=${RUN_EC} sql=$(sql_count "${A1B}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 2: 0001-0008 + --modules core records 8, writes 0 ---
echo "-- 2 core clone 0001-0008 --"
A2="${TMP}/case2"
copy_sql_range "${A2}/migrations" 1 8
run_sync --app "${A2}" --modules core
if [[ "${RUN_EC}" -eq 0 && "$(manifest_count "${A2}/kit-schema-manifest.json")" == "${#CORE_IDS[@]}" && "$(sql_count "${A2}/migrations")" == "8" ]]; then
  pass "2 core records ${#CORE_IDS[@]} writes 0"
else
  fail_case "2 core records ${#CORE_IDS[@]} writes 0" \
    "exit=${RUN_EC} modules=$(manifest_count "${A2}/kit-schema-manifest.json") sql=$(sql_count "${A2}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 3: isolated tree --modules core,audit appends 0009_kit_rate_limit_audit.sql ---
echo "-- 3 append audit as 0009_kit_* --"
A3="${TMP}/case3"
copy_sql_range "${A3}/migrations" 1 8
run_sync --app "${A3}" --modules core
if [[ "${RUN_EC}" -ne 0 ]]; then
  fail_case "3 seed core" "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
run_sync --app "${A3}" --modules core,audit
want3="${A3}/migrations/0009_kit_rate_limit_audit.sql"
expected_appended "${TMP}/expected-audit.sql" "rate_limit_audit" \
  "${KIT_SQL}/0010_rate_limit_audit.sql" \
  "apps/example-api/migrations/0010_rate_limit_audit.sql"
if [[ "${RUN_EC}" -eq 0 && -f "${want3}" && "$(sql_count "${A3}/migrations")" == "9" ]] \
  && cmp -s "${want3}" "${TMP}/expected-audit.sql"; then
  pass "3 writes 0009_kit_rate_limit_audit.sql (header + kit 0010)"
else
  fail_case "3 writes 0009_kit_rate_limit_audit.sql" \
    "exit=${RUN_EC} sql=$(sql_count "${A3}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
run_sync --app "${A3}" --modules core,audit
if [[ "${RUN_EC}" -eq 0 && "$(sql_count "${A3}/migrations")" == "9" ]]; then
  pass "3 second run writes 0"
else
  fail_case "3 second run writes 0" \
    "exit=${RUN_EC} sql=$(sql_count "${A3}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 3b: header recovery — delete manifest, headed file is recorded, not rewritten ---
echo "-- 3b header recovery --"
cp "${want3}" "${TMP}/audit-before-header.sql"
rm -f "${A3}/kit-schema-manifest.json"
run_sync --app "${A3}" --modules core,audit
if [[ "${RUN_EC}" -eq 0 && "$(sql_count "${A3}/migrations")" == "9" ]] \
  && cmp -s "${want3}" "${TMP}/audit-before-header.sql" \
  && [[ "$(manifest_field "${A3}/kit-schema-manifest.json" rate_limit_audit productFile)" == "migrations/0009_kit_rate_limit_audit.sql" ]]; then
  pass "3b header recovery records existing 0009_kit_* writes 0"
else
  fail_case "3b header recovery records existing 0009_kit_*" \
    "exit=${RUN_EC} sql=$(sql_count "${A3}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 4: product 0009_lgu_domain.sql + core files → rbac writes 0010_kit_organization_roles.sql ---
echo "-- 4 skip occupied 0009 --"
A4="${TMP}/case4"
copy_sql_range "${A4}/migrations" 1 8
printf '%s\n' "-- product domain" "CREATE TABLE IF NOT EXISTS lgu_domain (id TEXT PRIMARY KEY);" \
  >"${A4}/migrations/0009_lgu_domain.sql"
run_sync --app "${A4}" --modules rbac
want4="${A4}/migrations/0010_kit_organization_roles.sql"
if [[ "${RUN_EC}" -eq 0 && -f "${want4}" && ! -f "${A4}/migrations/0009_kit_organization_roles.sql" \
  && -f "${A4}/migrations/0009_lgu_domain.sql" && "$(sql_count "${A4}/migrations")" == "10" ]]; then
  pass "4 writes 0010_kit_organization_roles.sql not 0009"
else
  fail_case "4 writes 0010_kit_organization_roles.sql not 0009" \
    "exit=${RUN_EC} sql=$(sql_count "${A4}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 5: recorded sha mutated → exit 1 ---
echo "-- 5 mutated manifest sha --"
A5="${TMP}/case5"
copy_sql_range "${A5}/migrations" 1 8
run_sync --app "${A5}" --modules core
if [[ "${RUN_EC}" -ne 0 ]]; then
  fail_case "5 seed core" "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
KIT_SCHEMA_MANIFEST="${A5}/kit-schema-manifest.json" bun -e '
const fs = require("fs");
const p = process.env.KIT_SCHEMA_MANIFEST;
const m = JSON.parse(fs.readFileSync(p, "utf8"));
m.modules.init.kitSha256 = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef";
fs.writeFileSync(p, JSON.stringify(m, null, 2) + "\n");
'
sql_before5="$(sql_count "${A5}/migrations")"
run_sync --app "${A5}" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"module init mutated"* && "$(sql_count "${A5}/migrations")" == "${sql_before5}" ]]; then
  pass "5 mutated sha exits 1, no write"
else
  fail_case "5 mutated sha exits 1, no write" \
    "exit=${RUN_EC} sql=$(sql_count "${A5}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 6: dry-run prints filename, does not create it ---
echo "-- 6 dry-run --"
A6="${TMP}/case6"
copy_sql_range "${A6}/migrations" 1 8
run_sync --app "${A6}" --modules core,audit --dry-run
if [[ "${RUN_EC}" -eq 0 && "${RUN_OUT}" == *"0009_kit_rate_limit_audit.sql"* \
  && ! -f "${A6}/migrations/0009_kit_rate_limit_audit.sql" && "$(sql_count "${A6}/migrations")" == "8" \
  && ! -f "${A6}/kit-schema-manifest.json" ]]; then
  pass "6 dry-run prints 0009_kit_rate_limit_audit.sql and writes nothing"
else
  fail_case "6 dry-run prints planned file, writes nothing" \
    "exit=${RUN_EC} sql=$(sql_count "${A6}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 7: --modules all on empty migrations writes NNNN_kit_*.sql in catalog order ---
echo "-- 7 empty all --"
A7="${TMP}/case7"
mkdir -p "${A7}/migrations"
run_sync --app "${A7}" --modules all
ok7=1
detail7=""
if [[ "${RUN_EC}" -ne 0 ]]; then
  ok7=0
  detail7="exit ${RUN_EC}: $(echo "${RUN_OUT}" | tr '\n' ' ')"
elif [[ "$(sql_count "${A7}/migrations")" != "${#CATALOG_IDS[@]}" ]]; then
  ok7=0
  detail7="sql count=$(sql_count "${A7}/migrations")"
elif [[ "$(manifest_count "${A7}/kit-schema-manifest.json")" != "${#CATALOG_IDS[@]}" ]]; then
  ok7=0
  detail7="manifest count=$(manifest_count "${A7}/kit-schema-manifest.json")"
else
  n=1
  for id in "${CATALOG_IDS[@]}"; do
    nnnn="$(printf '%04d' "${n}")"
    f="${A7}/migrations/${nnnn}_kit_${id}.sql"
    if [[ ! -f "${f}" ]]; then
      ok7=0
      detail7="missing ${nnnn}_kit_${id}.sql"
      break
    fi
    head1="$(head -n 1 "${f}")"
    if [[ "${head1}" != "-- kit-schema: ${id}" ]]; then
      ok7=0
      detail7="${f} header=${head1}"
      break
    fi
    n=$((n + 1))
  done
  if [[ "${ok7}" -eq 1 ]]; then
    expected_appended "${TMP}/expected-init.sql" "init" \
      "${KIT_SQL}/0001_init.sql" \
      "apps/example-api/migrations/0001_init.sql"
    if ! cmp -s "${A7}/migrations/0001_kit_init.sql" "${TMP}/expected-init.sql"; then
      ok7=0
      detail7="0001_kit_init.sql body mismatch"
    fi
  fi
fi
if [[ "${ok7}" -eq 1 ]]; then
  pass "7 all on empty writes catalog-ordered kit_ files"
else
  fail_case "7 all on empty writes catalog-ordered kit_ files" "${detail7}"
fi

# --- 8: empty --modules ---
echo "-- 8 empty modules --"
A8="${TMP}/case8"
mkdir -p "${A8}/migrations"
run_sync --app "${A8}" --modules ""
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"empty"* ]]; then
  pass "8 empty --modules exits 1"
else
  fail_case "8 empty --modules exits 1" "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 9: unknown set ---
echo "-- 9 unknown set --"
run_sync --app "${A8}" --modules nope
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"unknown module set"* ]]; then
  pass "9 unknown set exits 1"
else
  fail_case "9 unknown set exits 1" "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 10: refuse apps/example-api ---
echo "-- 10 refuse example-api --"
sql_ex="$(sql_count "${KIT_SQL}")"
run_sync --app "${ROOT}/apps/example-api" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"refuse apps/example-"* \
  && "$(sql_count "${KIT_SQL}")" == "${sql_ex}" \
  && ! -f "${ROOT}/apps/example-api/kit-schema-manifest.json" ]]; then
  pass "10 refuse --app apps/example-api"
else
  fail_case "10 refuse --app apps/example-api" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 10b: refuse relative --app apps/example-* (same fail-closed) ---
echo "-- 10b refuse relative example-* --"
run_sync --app "apps/example-api" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"refuse apps/example-"* \
  && "$(sql_count "${KIT_SQL}")" == "${sql_ex}" ]]; then
  pass "10b refuse --app apps/example-api (relative)"
else
  fail_case "10b refuse --app apps/example-api (relative)" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
run_sync --app "apps/example-web" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"refuse apps/example-"* ]]; then
  pass "10b refuse --app apps/example-web"
else
  fail_case "10b refuse --app apps/example-web" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 11b: --modules all,typo still validates the typo ---
echo "-- 11b all+typo --"
run_sync --app "${A8}" --modules all,nope
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"unknown module set"* ]]; then
  pass "11b --modules all,nope exits 1"
else
  fail_case "11b --modules all,nope exits 1" "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 12: product 1000_ does not steal kit 0009 ---
echo "-- 12 kit band ignores 1000_ --"
A12="${TMP}/case12"
copy_sql_range "${A12}/migrations" 1 8
printf '%s\n' "-- product domain" "CREATE TABLE IF NOT EXISTS lgu_domain (id TEXT PRIMARY KEY);" \
  >"${A12}/migrations/1000_lgu_domain.sql"
run_sync --app "${A12}" --modules audit
if [[ "${RUN_EC}" -eq 0 && -f "${A12}/migrations/0009_kit_rate_limit_audit.sql" \
  && ! -f "${A12}/migrations/1001_kit_rate_limit_audit.sql" \
  && -f "${A12}/migrations/1000_lgu_domain.sql" ]]; then
  pass "12 1000_domain + audit writes 0009_kit_* not 1001"
else
  fail_case "12 1000_domain + audit writes 0009_kit_* not 1001" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 11: corrupt clone + --adopt does not rewrite ---
echo "-- 11 adopt mutated clone --"
A11="${TMP}/case11"
copy_sql_range "${A11}/migrations" 1 8
printf '\n-- corrupted\n' >>"${A11}/migrations/0001_init.sql"
run_sync --app "${A11}" --modules core --adopt
if [[ "${RUN_EC}" -ne 0 && "${RUN_OUT}" == *"adopt unmatched"* \
  && ! -f "${A11}/migrations/0009_kit_init.sql" ]] \
  && grep -q "corrupted" "${A11}/migrations/0001_init.sql"; then
  pass "11 adopt on mutated 0001 exits 1, no rewrite"
else
  fail_case "11 adopt on mutated 0001 exits 1, no rewrite" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 13: catalog pin mismatch via KIT_SCHEMA_CATALOG ---
echo "-- 13 catalog pin mismatch --"
A13="${TMP}/case13"
copy_sql_range "${A13}/migrations" 1 8
BAD_CAT="${TMP}/bad-catalog.json"
KIT_SCHEMA_OUT="${BAD_CAT}" KIT_SCHEMA_CATALOG="${CATALOG}" bun -e '
const fs = require("fs");
const m = JSON.parse(fs.readFileSync(process.env.KIT_SCHEMA_CATALOG, "utf8"));
m.modules[0].kitSha256 = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
fs.writeFileSync(process.env.KIT_SCHEMA_OUT, JSON.stringify(m, null, 2) + "\n");
'
set +e
RUN_OUT="$(KIT_SCHEMA_CATALOG="${BAD_CAT}" bash "${SCRIPT}" --app "${A13}" --modules core 2>&1)"
RUN_EC=$?
set -e
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"catalog pin mismatch"* \
  && "$(sql_count "${A13}/migrations")" == "8" ]]; then
  pass "13 catalog pin mismatch exits 1, no write"
else
  fail_case "13 catalog pin mismatch exits 1, no write" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 14: headed body drifted, no manifest → die, no extra kit file ---
echo "-- 14 headed body drifted --"
A14="${TMP}/case14"
copy_sql_range "${A14}/migrations" 1 8
run_sync --app "${A14}" --modules core
if [[ "${RUN_EC}" -ne 0 ]]; then
  fail_case "14 seed core" "exit=${RUN_EC}"
fi
run_sync --app "${A14}" --modules core,audit
printf '\n-- smuggled\n' >>"${A14}/migrations/0009_kit_rate_limit_audit.sql"
rm -f "${A14}/kit-schema-manifest.json"
sql_before14="$(sql_count "${A14}/migrations")"
run_sync --app "${A14}" --modules core,audit
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"headed rate_limit_audit drifted"* \
  && "$(sql_count "${A14}/migrations")" == "${sql_before14}" \
  && ! -f "${A14}/migrations/0010_kit_rate_limit_audit.sql" ]]; then
  pass "14 headed body drifted dies, no append"
else
  fail_case "14 headed body drifted dies, no append" \
    "exit=${RUN_EC} sql=$(sql_count "${A14}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 15: recorded body drifted ---
echo "-- 15 recorded body drifted --"
A15="${TMP}/case15"
copy_sql_range "${A15}/migrations" 1 8
run_sync --app "${A15}" --modules core
if [[ "${RUN_EC}" -ne 0 ]]; then
  fail_case "15 seed core" "exit=${RUN_EC}"
fi
printf '\n-- mutated body\n' >>"${A15}/migrations/0001_init.sql"
sql_before15="$(sql_count "${A15}/migrations")"
run_sync --app "${A15}" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"body drifted"* \
  && "$(sql_count "${A15}/migrations")" == "${sql_before15}" ]]; then
  pass "15 recorded body drifted exits 1, no write"
else
  fail_case "15 recorded body drifted exits 1, no write" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 16: recorded file missing ---
echo "-- 16 recorded missing --"
A16="${TMP}/case16"
copy_sql_range "${A16}/migrations" 1 8
run_sync --app "${A16}" --modules core
if [[ "${RUN_EC}" -ne 0 ]]; then
  fail_case "16 seed core" "exit=${RUN_EC}"
fi
rm -f "${A16}/migrations/0001_init.sql"
run_sync --app "${A16}" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"recorded init missing"* ]]; then
  pass "16 recorded missing file exits 1"
else
  fail_case "16 recorded missing file exits 1" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 17: kit band overflow at 0999 ---
echo "-- 17 band overflow --"
A17="${TMP}/case17"
copy_sql_range "${A17}/migrations" 1 8
printf '%s\n' "-- pad" >"${A17}/migrations/0999_pad.sql"
run_sync --app "${A17}" --modules audit
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"kit migration band overflow"* \
  && ! -f "${A17}/migrations/1000_kit_rate_limit_audit.sql" ]]; then
  pass "17 0999 pad + audit overflows, no 1000_kit_*"
else
  fail_case "17 0999 pad + audit overflows, no 1000_kit_*" \
    "exit=${RUN_EC} out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

echo "== summary: ${PASS} pass, ${FAIL} fail =="
if [[ "${FAIL}" -ne 0 ]]; then
  exit 1
fi
echo "kit-schema-sync: OK"
exit 0
