#!/usr/bin/env bash
# Table-driven harness for scripts/kit-schema-sync.sh
#
# Exit 0 only if all cases pass.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT="${ROOT}/scripts/kit-schema-sync.sh"
KIT_SQL="${ROOT}/apps/example-api/migrations"
CATALOG_IDS=(
  init
  api_keys_prefix
  kit_modules
  kit_modules_config
  better_auth
  better_auth_organization
  rbac_modules
  api_keys_organization
  organization_roles
  rate_limit_audit
  demo_items
  flows_plans_runs
  tasks_comments
)

if [[ ! -f "${SCRIPT}" ]]; then
  echo "FAIL: missing ${SCRIPT}" >&2
  exit 1
fi
chmod +x "${SCRIPT}" 2>/dev/null || true

PASS=0
FAIL=0

pass() {
  echo "  PASS: $1"
  PASS=$((PASS + 1))
}

fail_case() {
  echo "  FAIL: $1" >&2
  if [[ -n "${2:-}" ]]; then
    echo "    $2" >&2
  fi
  FAIL=$((FAIL + 1))
}

file_sha256() {
  local f="$1"
  local out
  if command -v sha256sum >/dev/null 2>&1; then
    out="$(sha256sum -- "$f")"
  else
    out="$(shasum -a 256 -- "$f")"
  fi
  printf '%s' "${out%% *}" | tr 'A-F' 'a-f'
}

sql_count() {
  local dir="$1"
  local files=()
  shopt -s nullglob
  files=("${dir}"/*.sql)
  printf '%s' "${#files[@]}"
}

manifest_count() {
  local f="$1"
  if [[ ! -f "${f}" ]]; then
    printf '0'
    return
  fi
  KIT_SCHEMA_MANIFEST="$f" bun -e '
const m = JSON.parse(require("fs").readFileSync(process.env.KIT_SCHEMA_MANIFEST, "utf8"));
console.log(Object.keys(m.modules || {}).length);
'
}

manifest_field() {
  local f="$1"
  local id="$2"
  local field="$3"
  KIT_SCHEMA_MANIFEST="$f" KIT_SCHEMA_ID="$id" KIT_SCHEMA_FIELD="$field" bun -e '
const m = JSON.parse(require("fs").readFileSync(process.env.KIT_SCHEMA_MANIFEST, "utf8"));
const e = m.modules && m.modules[process.env.KIT_SCHEMA_ID];
if (!e) process.exit(2);
const v = e[process.env.KIT_SCHEMA_FIELD];
if (typeof v !== "string") process.exit(2);
console.log(v);
'
}

copy_sql_range() {
  local dest="$1"
  local start="$2"
  local end="$3"
  local n name
  mkdir -p "${dest}"
  for n in $(seq "${start}" "${end}"); do
    name="$(printf '%04d' "${n}")"
    cp "${KIT_SQL}/${name}"_*.sql "${dest}/"
  done
}

expected_appended() {
  local dest="$1"
  local id="$2"
  local kit_file="$3"
  local src_rel="$4"
  {
    printf -- '-- kit-schema: %s\n' "${id}"
    printf -- '-- kit-sha256: %s\n' "$(file_sha256 "${kit_file}")"
    printf -- '-- kit-source: %s\n' "${src_rel}"
    printf -- '-- Do not edit this file. Kit changes ship as a new module id.\n'
    printf '\n'
    cat "${kit_file}"
  } >"${dest}"
}

run_sync() {
  set +e
  RUN_OUT="$("${SCRIPT}" "$@" 2>&1)"
  RUN_EC=$?
  set -e
}

echo "== kit-schema-sync =="
TMP="$(mktemp -d -t kit-schema-sync-XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

# --- 1: adopt on a full copy records all 13, writes no SQL ---
echo "-- 1 adopt full copy --"
A1="${TMP}/case1"
mkdir -p "${A1}/migrations"
cp "${KIT_SQL}"/*.sql "${A1}/migrations/"
before_1="$(sql_count "${A1}/migrations")"
run_sync --app "${A1}" --modules all --adopt
if [[ "${RUN_EC}" -eq 0 ]]; then
  pass "1 adopt exit 0"
else
  fail_case "1 adopt exit 0" "exit ${RUN_EC}: $(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
if [[ "$(sql_count "${A1}/migrations")" == "${before_1}" && "${before_1}" == "13" ]]; then
  pass "1 adopt writes 0 sql (still 13)"
else
  fail_case "1 adopt writes 0 sql" "count=$(sql_count "${A1}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
if [[ "$(manifest_count "${A1}/kit-schema-manifest.json")" == "13" ]]; then
  pass "1 adopt records 13 modules"
else
  fail_case "1 adopt records 13 modules" "count=$(manifest_count "${A1}/kit-schema-manifest.json")"
fi
if [[ "$(manifest_field "${A1}/kit-schema-manifest.json" init productFile)" == "migrations/0001_init.sql" ]]; then
  pass "1 adopt productFile stays 0001_init.sql"
else
  fail_case "1 adopt productFile stays 0001_init.sql" \
    "got=$(manifest_field "${A1}/kit-schema-manifest.json" init productFile 2>/dev/null || true)"
fi

# --- 2: 0001-0008 + --modules core records 8, writes 0 ---
echo "-- 2 core clone 0001-0008 --"
A2="${TMP}/case2"
copy_sql_range "${A2}/migrations" 1 8
run_sync --app "${A2}" --modules core
if [[ "${RUN_EC}" -eq 0 && "$(manifest_count "${A2}/kit-schema-manifest.json")" == "8" && "$(sql_count "${A2}/migrations")" == "8" ]]; then
  pass "2 core records 8 writes 0"
else
  fail_case "2 core records 8 writes 0" \
    "exit=${RUN_EC} modules=$(manifest_count "${A2}/kit-schema-manifest.json") sql=$(sql_count "${A2}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 3: same tree --modules core,audit appends 0009_kit_rate_limit_audit.sql ---
echo "-- 3 append audit as 0009_kit_* --"
run_sync --app "${A2}" --modules core,audit
want3="${A2}/migrations/0009_kit_rate_limit_audit.sql"
expected_appended "${TMP}/expected-audit.sql" "rate_limit_audit" \
  "${KIT_SQL}/0010_rate_limit_audit.sql" \
  "apps/example-api/migrations/0010_rate_limit_audit.sql"
if [[ "${RUN_EC}" -eq 0 && -f "${want3}" && "$(sql_count "${A2}/migrations")" == "9" ]] \
  && cmp -s "${want3}" "${TMP}/expected-audit.sql"; then
  pass "3 writes 0009_kit_rate_limit_audit.sql (header + kit 0010)"
else
  fail_case "3 writes 0009_kit_rate_limit_audit.sql" \
    "exit=${RUN_EC} sql=$(sql_count "${A2}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi
run_sync --app "${A2}" --modules core,audit
if [[ "${RUN_EC}" -eq 0 && "$(sql_count "${A2}/migrations")" == "9" ]]; then
  pass "3 second run writes 0"
else
  fail_case "3 second run writes 0" \
    "exit=${RUN_EC} sql=$(sql_count "${A2}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 4: product 0009_lgu_domain.sql + core files → rbac writes 0010_kit_organization_roles.sql ---
echo "-- 4 skip occupied 0009 --"
A4="${TMP}/case4"
copy_sql_range "${A4}/migrations" 1 8
printf '%s\n' "-- product domain" "CREATE TABLE IF NOT EXISTS lgu_domain (id TEXT PRIMARY KEY);" \
  >"${A4}/migrations/0009_lgu_domain.sql"
run_sync --app "${A4}" --modules rbac
want4="${A4}/migrations/0010_kit_organization_roles.sql"
if [[ "${RUN_EC}" -eq 0 && -f "${want4}" && ! -f "${A4}/migrations/0009_kit_organization_roles.sql" \
  && -f "${A4}/migrations/0009_lgu_domain.sql" && "$(sql_count "${A4}/migrations")" == "10" ]]; then
  pass "4 writes 0010_kit_organization_roles.sql not 0009"
else
  fail_case "4 writes 0010_kit_organization_roles.sql not 0009" \
    "exit=${RUN_EC} sql=$(sql_count "${A4}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 5: recorded sha mutated → exit 1 ---
echo "-- 5 mutated manifest sha --"
A5="${TMP}/case5"
copy_sql_range "${A5}/migrations" 1 8
run_sync --app "${A5}" --modules core
KIT_SCHEMA_MANIFEST="${A5}/kit-schema-manifest.json" bun -e '
const fs = require("fs");
const p = process.env.KIT_SCHEMA_MANIFEST;
const m = JSON.parse(fs.readFileSync(p, "utf8"));
m.modules.init.kitSha256 = "deadbeef";
fs.writeFileSync(p, JSON.stringify(m, null, 2) + "\n");
'
sql_before5="$(sql_count "${A5}/migrations")"
run_sync --app "${A5}" --modules core
if [[ "${RUN_EC}" -eq 1 && "${RUN_OUT}" == *"module init mutated"* && "$(sql_count "${A5}/migrations")" == "${sql_before5}" ]]; then
  pass "5 mutated sha exits 1, no write"
else
  fail_case "5 mutated sha exits 1, no write" \
    "exit=${RUN_EC} sql=$(sql_count "${A5}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 6: dry-run of case 3 prints filename, does not create it ---
echo "-- 6 dry-run --"
A6="${TMP}/case6"
copy_sql_range "${A6}/migrations" 1 8
run_sync --app "${A6}" --modules core,audit --dry-run
if [[ "${RUN_EC}" -eq 0 && "${RUN_OUT}" == *"0009_kit_rate_limit_audit.sql"* \
  && ! -f "${A6}/migrations/0009_kit_rate_limit_audit.sql" && "$(sql_count "${A6}/migrations")" == "8" \
  && ! -f "${A6}/kit-schema-manifest.json" ]]; then
  pass "6 dry-run prints 0009_kit_rate_limit_audit.sql and writes nothing"
else
  fail_case "6 dry-run prints planned file, writes nothing" \
    "exit=${RUN_EC} sql=$(sql_count "${A6}/migrations") out=$(echo "${RUN_OUT}" | tr '\n' ' ')"
fi

# --- 7: --modules all on empty migrations writes 0001..0013_kit_*.sql in catalog order ---
echo "-- 7 empty all --"
A7="${TMP}/case7"
mkdir -p "${A7}/migrations"
run_sync --app "${A7}" --modules all
ok7=1
detail7=""
if [[ "${RUN_EC}" -ne 0 ]]; then
  ok7=0
  detail7="exit ${RUN_EC}: $(echo "${RUN_OUT}" | tr '\n' ' ')"
elif [[ "$(sql_count "${A7}/migrations")" != "13" ]]; then
  ok7=0
  detail7="sql count=$(sql_count "${A7}/migrations")"
else
  n=1
  for id in "${CATALOG_IDS[@]}"; do
    nnnn="$(printf '%04d' "${n}")"
    f="${A7}/migrations/${nnnn}_kit_${id}.sql"
    if [[ ! -f "${f}" ]]; then
      ok7=0
      detail7="missing ${nnnn}_kit_${id}.sql"
      break
    fi
    head1="$(head -n 1 "${f}")"
    if [[ "${head1}" != "-- kit-schema: ${id}" ]]; then
      ok7=0
      detail7="${f} header=${head1}"
      break
    fi
    n=$((n + 1))
  done
fi
if [[ "${ok7}" -eq 1 ]]; then
  pass "7 all on empty writes 0001..0013_kit_*.sql in catalog order"
else
  fail_case "7 all on empty writes 13 sequential kit_ files" "${detail7}"
fi

echo "== summary: ${PASS} pass, ${FAIL} fail =="
if [[ "${FAIL}" -ne 0 ]]; then
  exit 1
fi
echo "kit-schema-sync: OK"
exit 0
