#!/usr/bin/env bash
# Generated by dev-core worktreeScaffold — concerns: env-files, bun-install-warmup, lefthook-hookspath-fix
# Plus Chemin A extras: apps/example-api/.dev.vars.example
# Re-generate base with worktreeScaffold; keep CF block when re-composing.
set -euo pipefail

# ─── env-files ──────────────────────────────────────────
if [ -f .env.example ] && [ ! -f .env ]; then
  cp .env.example .env
  echo "worktree-setup: created .env from .env.example"
fi

# Cloudflare Worker local secrets (gitignored) — kit demo API
if [ -f apps/example-api/.dev.vars.example ] && [ ! -f apps/example-api/.dev.vars ]; then
  cp apps/example-api/.dev.vars.example apps/example-api/.dev.vars
  echo "worktree-setup: created apps/example-api/.dev.vars from .dev.vars.example"
fi

# ─── bun-install-warmup ──────────────────────────────────────────
bun install

# ─── lefthook-hookspath-fix ──────────────────────────────────────────
# in worktrees, lefthook installs core.hooksPath relative to the worktree git dir (wrong —
# git uses the common dir for hooks). unset so git falls back to the default hooks path.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
GIT_COMMON_DIR=$(git rev-parse --git-common-dir 2>/dev/null)
if [ "${GIT_DIR}" != "${GIT_COMMON_DIR}" ]; then
  git config --unset-all core.hooksPath 2>/dev/null || true
fi
