#!/usr/bin/env bash
# Generated by dev-core worktreeScaffold — teardown (noop for env/bun/lefthook concerns)
set -euo pipefail

# env-files: stay in worktree after teardown
# bun-install-warmup: noop
# lefthook-hookspath-fix: noop
:
